[providers.python]
requirements = "requirements.txt"

[phases.setup]
nixPkgs = ["python310", "gcc", "gfortran", "blas", "lapack"]

[phases.build]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
